name: Feature request
description: Suggest an idea or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Idun Agent Platform. Please describe the problem and your proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to achieve? What’s painful today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added/changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
