"""sso table

Revision ID: 73f9ed38d018
Revises: a1c0d2e3f4b5
Create Date: 2026-05-06 10:29:28.877649
"""
from alembic import op
import sqlalchemy as sa


revision = '73f9ed38d018'
down_revision = 'a1c0d2e3f4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standalone_sso',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sso_config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standalone_sso')
    # ### end Alembic commands ###
