"""Add base_url in managed_agent

Revision ID: 42d49e3bc5f7
Revises: 5aa453389806
Create Date: 2025-11-29 16:44:32.917782+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '42d49e3bc5f7'
down_revision: Union[str, None] = '5aa453389806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agents', sa.Column('base_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_agents', 'base_url')
    # ### end Alembic commands ###
