"""add tenant and workspace id fields

Revision ID: d874b00b9e41
Revises: 11cb06e2e52a
Create Date: 2025-10-08 08:46:49.787976+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd874b00b9e41'
down_revision: Union[str, None] = '11cb06e2e52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_deployment_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_deployment_config_managed_engine_id'), table_name='deployment_config')
    op.drop_table('deployment_config')
    op.drop_index(op.f('ix_deployments_agent_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_managed_engine_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_retriever_config_managed_engine_id'), table_name='retriever_config')
    op.drop_table('retriever_config')
    op.add_column('engine', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('engine', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_engine_tenant_id'), 'engine', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_engine_workspace_id'), 'engine', ['workspace_id'], unique=False)
    op.add_column('gateway_routes', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('gateway_routes', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_gateway_routes_tenant_id'), 'gateway_routes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gateway_routes_workspace_id'), 'gateway_routes', ['workspace_id'], unique=False)
    op.add_column('managed_agents', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('managed_agents', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_agent_config_name'), table_name='managed_agents')
    op.create_index(op.f('ix_managed_agents_name'), 'managed_agents', ['name'], unique=False)
    op.create_index(op.f('ix_managed_agents_tenant_id'), 'managed_agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_managed_agents_workspace_id'), 'managed_agents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_agents_workspace_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_tenant_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_name'), table_name='managed_agents')
    op.create_index(op.f('ix_agent_config_name'), 'managed_agents', ['name'], unique=False)
    op.drop_column('managed_agents', 'workspace_id')
    op.drop_column('managed_agents', 'tenant_id')
    op.drop_index(op.f('ix_gateway_routes_workspace_id'), table_name='gateway_routes')
    op.drop_index(op.f('ix_gateway_routes_tenant_id'), table_name='gateway_routes')
    op.drop_column('gateway_routes', 'workspace_id')
    op.drop_column('gateway_routes', 'tenant_id')
    op.drop_index(op.f('ix_engine_workspace_id'), table_name='engine')
    op.drop_index(op.f('ix_engine_tenant_id'), table_name='engine')
    op.drop_column('engine', 'workspace_id')
    op.drop_column('engine', 'tenant_id')
    op.create_table('retriever_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('retriever_config_pkey'))
    )
    op.create_index(op.f('ix_retriever_config_managed_engine_id'), 'retriever_config', ['managed_engine_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('docker_sha', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['managed_agents.id'], name='deployments_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deployments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_deployments_managed_engine_id'), 'deployments', ['managed_engine_id'], unique=False)
    op.create_index(op.f('ix_deployments_agent_id'), 'deployments', ['agent_id'], unique=False)
    op.create_table('deployment_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deployment_config_pkey'))
    )
    op.create_index(op.f('ix_deployment_config_managed_engine_id'), 'deployment_config', ['managed_engine_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('artifacts_deployment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_index(op.f('ix_artifacts_deployment_id'), 'artifacts', ['deployment_id'], unique=False)
    # ### end Alembic commands ###
