"""initial managed_agents

Revision ID: ff7f22c5cc78
Revises:
Create Date: 2025-10-16 17:06:44.450476+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7f22c5cc78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engine_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_agents_agent_hash'), 'managed_agents', ['agent_hash'], unique=False)
    op.create_index(op.f('ix_managed_agents_tenant_id'), 'managed_agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_managed_agents_workspace_id'), 'managed_agents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_agents_workspace_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_tenant_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_agent_hash'), table_name='managed_agents')
    op.drop_table('managed_agents')
    # ### end Alembic commands ###
