"""managed_agents remove workspace and tenant

Revision ID: 62635f8fc657
Revises: ff7f22c5cc78
Create Date: 2025-10-17 11:59:20.432992+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '62635f8fc657'
down_revision: Union[str, None] = 'ff7f22c5cc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_agents_tenant_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_workspace_id'), table_name='managed_agents')
    op.drop_column('managed_agents', 'workspace_id')
    op.drop_column('managed_agents', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agents', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('managed_agents', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_managed_agents_workspace_id'), 'managed_agents', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_managed_agents_tenant_id'), 'managed_agents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
