"""Add managed_observabilities and add name in mcp_server

Revision ID: 92b2983e3c1a
Revises: bdc4b198abf1
Create Date: 2025-11-23 15:01:28.980522+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b2983e3c1a'
down_revision: Union[str, None] = 'bdc4b198abf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_observabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('observability_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('managed_mcp_servers', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('managed_mcp_servers', sa.Column('mcp_server_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('managed_mcp_servers', 'mcp_server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_mcp_servers', sa.Column('mcp_server', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('managed_mcp_servers', 'mcp_server_config')
    op.drop_column('managed_mcp_servers', 'name')
    op.drop_table('managed_observabilities')
    # ### end Alembic commands ###
