"""managed_agents add status and version

Revision ID: c61a1639e45a
Revises: 62635f8fc657
Create Date: 2025-10-17 12:28:03.889770+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c61a1639e45a'
down_revision: Union[str, None] = '62635f8fc657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agents', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('managed_agents', sa.Column('version', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_agents', 'version')
    op.drop_column('managed_agents', 'name')
    # ### end Alembic commands ###
