"""add agent-hash

Revision ID: d38262ff1942
Revises: 3e5dc695f9cc
Create Date: 2025-10-07 16:17:36.187440+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd38262ff1942'
down_revision: Union[str, None] = '3e5dc695f9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Just add the agent_hash field
    op.add_column('managed_agents', sa.Column('agent_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_managed_agents_agent_hash'), 'managed_agents', ['agent_hash'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_agents_workspace_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_tenant_id'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_name'), table_name='managed_agents')
    op.drop_index(op.f('ix_managed_agents_agent_hash'), table_name='managed_agents')
    op.create_index(op.f('ix_agent_config_workspace_id'), 'managed_agents', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_agent_config_tenant_id'), 'managed_agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_config_name'), 'managed_agents', ['name'], unique=False)
    op.drop_column('managed_agents', 'agent_hash')
    op.create_table('retriever_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('retriever_config_pkey'))
    )
    op.create_index(op.f('ix_retriever_config_workspace_id'), 'retriever_config', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_retriever_config_tenant_id'), 'retriever_config', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_retriever_config_managed_engine_id'), 'retriever_config', ['managed_engine_id'], unique=False)
    op.create_table('deployment_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deployment_config_pkey'))
    )
    op.create_index(op.f('ix_deployment_config_workspace_id'), 'deployment_config', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_deployment_config_tenant_id'), 'deployment_config', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deployment_config_managed_engine_id'), 'deployment_config', ['managed_engine_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('managed_engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('docker_sha', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['managed_agents.id'], name='deployments_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deployments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deployments_managed_engine_id'), 'deployments', ['managed_engine_id'], unique=False)
    op.create_index(op.f('ix_deployments_agent_id'), 'deployments', ['agent_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('artifacts_deployment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_index(op.f('ix_artifacts_workspace_id'), 'artifacts', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_artifacts_deployment_id'), 'artifacts', ['deployment_id'], unique=False)
    # ### end Alembic commands ###
