"""add managed prompts and assignments

Revision ID: a50bb3f44ec7
Revises: 4e21ee5d39eb
Create Date: 2026-03-03 16:15:02.428407+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a50bb3f44ec7'
down_revision: Union[str, None] = '4e21ee5d39eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'prompt_id', 'version', name='uq_workspace_prompt_version')
    )
    op.create_index(op.f('ix_managed_prompts_prompt_id'), 'managed_prompts', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_managed_prompts_workspace_id'), 'managed_prompts', ['workspace_id'], unique=False)
    op.create_table('agent_prompt_assignments',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['managed_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['managed_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'prompt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_prompt_assignments')
    op.drop_index(op.f('ix_managed_prompts_workspace_id'), table_name='managed_prompts')
    op.drop_index(op.f('ix_managed_prompts_prompt_id'), table_name='managed_prompts')
    op.drop_table('managed_prompts')
    # ### end Alembic commands ###
